/**
 * Cross-language conformance for `design_id`.
 *
 * `src/cxp/design-id.ts` is a port of `crux_cxp`'s `cxpDesignIdForPath`, and
 * the whole value of the token is that every peer keying the same folder
 * produces the same 16 hex characters. A port that is *almost* right does
 * not fail loudly: the producer writes `crux/cxp/workspace/<a>.json`, the
 * sender puts `<b>` on the wire, and the receiver looks up a design that
 * does not exist. Nothing throws; the feature simply never works.
 *
 * So this file does not assert against expectations its author wrote down.
 * It runs ONE shared corpus (`test/fixtures/design-id/corpus.json`) through
 * BOTH implementations and requires the two token sets to be equal, in three
 * layers of decreasing environmental dependence:
 *
 * 1. **Live cross-run** — spawns the real Dart `cxpDesignIdForPath` through
 *    `tool/dart-conformance/design_id_tokens.dart` over the very same
 *    materialised tree, same working directory, and compares every token
 *    byte-for-byte. This is the layer that catches a symlink, existence or
 *    case-folding drift, and it is the only layer that can. It needs the
 *    sibling `crux-shared` checkout and a Dart toolchain, both of which every
 *    development machine has and the crux-vscode CI runner has neither — see
 *    [describeCrossRun] for exactly what is skipped where.
 * 2. **Committed goldens** — `expected.json`, generated by that same Dart
 *    implementation, for the corpus's `lexical` cases (paths under a
 *    directory that cannot exist, so the answer does not depend on the
 *    machine). This layer runs everywhere, CI included.
 * 3. **Relational invariants** — the properties the derivation contract
 *    promises (a file and its folder agree; a trailing separator is
 *    irrelevant; a symlink and its target agree; different folders differ;
 *    the shape is `[0-9a-f]{16}`). These hold on any machine with no Dart at
 *    all, and they are what a reader should look at first to understand what
 *    the token means.
 *
 * **What makes it fail.** Change the truncation from 16 to 12, hash the
 * input instead of the containing directory, keep Node's trailing slash,
 * fold case on darwin, use `fs.realpathSync` instead of `.native`, or take
 * the parent of a directory that exists — layer 2 catches the first four and
 * layer 1 catches all six. Change the *Dart* side and layer 1 fails on the
 * next developer's run, which is the direction that matters most: this token
 * is on the wire, and the two implementations are not free to move apart.
 */
import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { afterAll, describe, expect, it } from 'vitest';
import { CXP_DESIGN_ID_PATTERN, cxpDesignIdForPath } from '../../src/cxp/design-id';

const FIXTURES = fileURLToPath(new URL('../fixtures/design-id', import.meta.url));
const REPO_ROOT = fileURLToPath(new URL('../../../..', import.meta.url));
const DART_HARNESS = path.join(REPO_ROOT, 'tool', 'dart-conformance', 'design_id_tokens.dart');
/**
 * The sibling checkout the reference implementation lives in, and the
 * package config that lets the harness import it with no `pub get` and — the
 * constraint that shaped this — no file written into that repository.
 */
const CRUX_SHARED_PACKAGE_CONFIG = path.join(
  REPO_ROOT,
  '..',
  'crux-shared',
  '.dart_tool',
  'package_config.json',
);

interface LexicalCase {
  readonly name: string;
  readonly input: string;
  readonly note: string;
}

interface FilesystemCase {
  readonly name: string;
  readonly input: string;
  readonly note: string;
}

interface Corpus {
  readonly lexical: readonly LexicalCase[];
  readonly filesystem: {
    readonly tree: {
      readonly directories: readonly string[];
      readonly files: readonly string[];
      readonly symlinks: readonly { readonly link: string; readonly target: string }[];
    };
    readonly cases: readonly FilesystemCase[];
  };
}

interface Goldens {
  readonly lexical: Readonly<Record<string, string>>;
}

const corpus = JSON.parse(readFileSync(path.join(FIXTURES, 'corpus.json'), 'utf8')) as Corpus;
const goldens = JSON.parse(readFileSync(path.join(FIXTURES, 'expected.json'), 'utf8')) as Goldens;

/**
 * Materialise the corpus tree once, in a fresh temp directory.
 *
 * Deliberately **not** `realpath`'d: on macOS `os.tmpdir()` sits under
 * `/var/folders/…` and `/var` is a symlink to `/private/var`, so leaving the
 * root as handed to us means every case exercises the symlink resolution the
 * derivation depends on rather than side-stepping it.
 */
const root = mkdtempSync(path.join(tmpdir(), 'crux-design-id-'));
for (const directory of corpus.filesystem.tree.directories) {
  mkdirSync(path.join(root, directory), { recursive: true });
}
for (const file of corpus.filesystem.tree.files) {
  writeFileSync(path.join(root, file), `// ${file}\n`, 'utf8');
}
for (const { link, target } of corpus.filesystem.tree.symlinks) {
  symlinkSync(target, path.join(root, link));
}

afterAll(() => {
  rmSync(root, { recursive: true, force: true });
});

/** A case's `{root}` placeholder replaced with the live temp root. */
function inputFor(template: string): string {
  return template.split('{root}').join(root);
}

const filesystemInputs = corpus.filesystem.cases.map((entry) => inputFor(entry.input));
const lexicalInputs = corpus.lexical.map((entry) => entry.input);
const allInputs = [...lexicalInputs, ...filesystemInputs];

/** Every corpus input, through the TypeScript port. */
function typescriptTokens(): Record<string, string> {
  const tokens: Record<string, string> = {};
  for (const input of allInputs) tokens[input] = cxpDesignIdForPath(input);
  return tokens;
}

function tokenOf(name: string): string {
  const entry = corpus.filesystem.cases.find((candidate) => candidate.name === name);
  if (entry === undefined) throw new Error(`no filesystem corpus case named ${name}`);
  return cxpDesignIdForPath(inputFor(entry.input));
}

describe('design_id — corpus integrity', () => {
  it('has a golden for every lexical case and a lexical case for every golden', () => {
    // Guards the corpus itself: a case added without regenerating the
    // goldens would otherwise silently assert nothing.
    expect(corpus.lexical.map((entry) => entry.name).sort()).toEqual(
      Object.keys(goldens.lexical).sort(),
    );
    expect(corpus.lexical.length).toBeGreaterThan(0);
    expect(corpus.filesystem.cases.length).toBeGreaterThan(0);
  });

  it('every case carries a note saying what it is for', () => {
    for (const entry of [...corpus.lexical, ...corpus.filesystem.cases]) {
      expect(entry.note.length, entry.name).toBeGreaterThan(0);
    }
  });
});

describe('design_id — goldens generated by the Dart implementation', () => {
  const posix = path.sep === '/';
  for (const entry of corpus.lexical) {
    // The lexical branch is platform-defined (Windows normalizes separators
    // and case-folds), so these tokens are POSIX tokens. On Windows the
    // cross-run below is what holds the two implementations together.
    it.skipIf(!posix)(`${entry.name} — ${entry.note}`, () => {
      expect(cxpDesignIdForPath(entry.input)).toBe(goldens.lexical[entry.name]);
    });
  }
});

describe('design_id — the contract, as relations that hold on any machine', () => {
  it('is always sixteen lowercase hex characters', () => {
    for (const [input, token] of Object.entries(typescriptTokens())) {
      expect(token, input).toMatch(CXP_DESIGN_ID_PATTERN);
    }
  });

  it('a file and the directory containing it name the same design', () => {
    expect(tokenOf('file-in-dir')).toBe(tokenOf('dir'));
    expect(tokenOf('other-file-in-dir')).toBe(tokenOf('dir'));
  });

  it('a trailing separator, and a doubled one, change nothing', () => {
    expect(tokenOf('dir-trailing-separator')).toBe(tokenOf('dir'));
    expect(tokenOf('dir-double-trailing-separator')).toBe(tokenOf('dir'));
  });

  it('`.` and `..` segments are collapsed before the directory is taken', () => {
    expect(tokenOf('dot-segments')).toBe(tokenOf('dir'));
    expect(tokenOf('parent-escape')).toBe(tokenOf('sibling-file'));
  });

  it('symlinks resolve — to the directory, and through it', () => {
    expect(tokenOf('symlinked-dir')).toBe(tokenOf('dir'));
    expect(tokenOf('file-through-symlinked-dir')).toBe(tokenOf('dir'));
    expect(tokenOf('symlinked-file')).toBe(tokenOf('dir'));
  });

  it('a file that does not exist yet still names its folder', () => {
    // The producer case: SimCrux keys the dump it is about to write.
    expect(tokenOf('missing-file-in-existing-dir')).toBe(tokenOf('dir'));
    expect(tokenOf('missing-dir-in-existing-dir')).toBe(tokenOf('dir'));
  });

  it('different directories are different designs', () => {
    const distinct = ['dir', 'nested-dir', 'sibling-file', 'missing-deep', 'root-itself'].map(
      tokenOf,
    );
    expect(new Set(distinct).size).toBe(distinct.length);
  });

  it('a nested folder is its own design, not its parent', () => {
    expect(tokenOf('nested-file')).toBe(tokenOf('nested-dir'));
    expect(tokenOf('nested-dir')).not.toBe(tokenOf('dir'));
  });
});

/**
 * Whether the live cross-run can happen here.
 *
 * Both halves are development-machine facts: the crux-shared checkout is a
 * separate repository, and crux-vscode's CI installs Node and nothing else.
 * Skipping is therefore normal in CI and abnormal anywhere a human is
 * working, which is why it logs rather than passing quietly — a silent skip
 * on a laptop is how a divergence would survive a whole session.
 */
function crossRunAvailable(): boolean {
  if (!existsSync(CRUX_SHARED_PACKAGE_CONFIG)) return false;
  if (!existsSync(DART_HARNESS)) return false;
  try {
    execFileSync('dart', ['--version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

const canCrossRun = crossRunAvailable();
if (!canCrossRun) {
  console.warn(
    '[design-id] cross-language conformance SKIPPED: needs a Dart toolchain and a ' +
      `crux-shared checkout at ${CRUX_SHARED_PACKAGE_CONFIG}. The committed goldens still ran.`,
  );
}

describe.skipIf(!canCrossRun)('design_id — live cross-run against crux_cxp', () => {
  it('produces byte-identical tokens for every case in the shared corpus', () => {
    const stdout = execFileSync(
      'dart',
      ['run', `--packages=${CRUX_SHARED_PACKAGE_CONFIG}`, DART_HARNESS],
      {
        input: JSON.stringify(allInputs),
        encoding: 'utf8',
        // The same working directory, because two of the corpus cases are
        // relative paths and both implementations canonicalize them against
        // the process's own cwd. A different cwd here would produce a
        // difference that is the harness's fault, not the port's.
        cwd: process.cwd(),
        timeout: 120_000,
      },
    );
    const dartTokens = JSON.parse(stdout) as Record<string, string>;
    expect(dartTokens).toEqual(typescriptTokens());
  });
});
