import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { JsonObject } from './json';

let tempCounter = 0;

/**
 * The scratch path a single atomic write to [filePath] will use.
 *
 * Shape: `<dest>.<micros>-<counter>.tmp`, byte-for-byte the convention
 * `crux_io`'s `writeStringAtomic` uses — which is why a real orphan does
 * **not** end in `.json.tmp`, it ends in `.tmp` with a discriminator in
 * between. Any sweeper that matches only `.json.tmp` lets every genuine
 * orphan through; see `CxpDiscovery`'s temp sweep.
 *
 * A fixed `<dest>.tmp` is not safe: two overlapping writes to the same
 * destination would each write *the same* scratch path, and the second
 * rename would find the file already consumed.
 */
export function atomicTempPath(filePath: string): string {
  tempCounter = (tempCounter + 1) % 1_000_000;
  const micros = Math.round(performance.timeOrigin * 1000 + performance.now() * 1000);
  return `${filePath}.${micros}-${tempCounter}.tmp`;
}

/**
 * Crash-safely replace [filePath] with the JSON encoding of [value].
 *
 * The bytes go to a uniquely-named sibling scratch file and are then
 * `rename`d over the destination. `rename` within a directory is atomic on
 * every filesystem the Crux products target, so a concurrent scanner
 * observes either the whole old manifest or the whole new one — never a
 * torn one. The parent directory is created if absent.
 *
 * No `fsync`: a peer manifest is discovery state, never a source of truth
 * — it is republished with a fresh `started_at` every heartbeat, and one
 * lost to a crash is regenerated by a process that had to restart anyway.
 * (`crux_io` calls this `WriteDurability.ephemeral`, and the manifest
 * writer is its only such call site in the suite.)
 *
 * On failure the scratch file is removed on a best-effort basis so a failed
 * write leaves no debris for a later scan to trip over, and the original
 * error is rethrown — this helper never swallows.
 */
export async function writeJsonAtomic(filePath: string, value: JsonObject): Promise<void> {
  await mkdir(dirname(filePath), { recursive: true });
  const temp = atomicTempPath(filePath);
  try {
    await writeFile(temp, `${JSON.stringify(value, undefined, 2)}\n`, 'utf8');
    await rename(temp, filePath);
  } catch (error) {
    await rm(temp, { force: true }).catch(() => undefined);
    throw error;
  }
}
