import type { ElementPathChoice, ElementPathResolver, EditorSelectionSnapshot } from '../editor/send';
import { resolveWorkspacePath, type WorkspacePathRefusal } from '../editor/workspace-paths';
import { hierarchyCandidates, type DesignHierarchyProvider } from './hierarchy';
import { isExactMatch, type NameCandidate, type NameIndex, type NameQuery } from './name-index';
import { fromStemsDescription, nameMatchDescription } from './strings';

/**
 * The name resolver: the index plus the hierarchy fallback, shaped as an
 * [ElementPathResolver].
 *
 * `passThroughElementPathResolver` sends the selected text verbatim, which
 * is right for a flat design and useless for a hierarchical one. This is the
 * stems-backed alternative — and it is wired in rather than merely
 * available (each product that keeps a stems index contributes one to the
 * window, see `window/api.ts`), because a resolver nobody constructs is a
 * resolver nobody notices is wrong.
 */

/** Why a design path could not be turned into a source location. */
export type SourceLocationRefusal =
  /** No stems entry maps that path to a file at all. */
  | 'unknown-path'
  /** A stems entry exists, but its file failed the §11 containment check. */
  | WorkspacePathRefusal;

/** Forward-direction result: a design path's declaration site. */
export type ResolvedSourceLocation =
  | {
      readonly ok: true;
      /** Real path, symlinks resolved, inside an open workspace folder. */
      readonly fsPath: string;
      /** 1-based line, as stems and CXP both count. */
      readonly lineNumber: number;
    }
  | { readonly ok: false; readonly reason: SourceLocationRefusal };

/** Construction options for [NameResolver]. */
export interface NameResolverOptions {
  /** The index to consult. Usually owned by a `StemsIndexService`. */
  readonly index: NameIndex;
  /**
   * Design hierarchy for the fallback. Omit for none — a window with no
   * Crux app running resolves from stems or not at all, which is correct.
   */
  readonly hierarchy?: DesignHierarchyProvider;
  /**
   * Open workspace folders, for [NameResolver.sourceLocationFor]'s
   * containment check. Same source as everywhere else:
   * `vscode.workspace.workspaceFolders`.
   */
  readonly workspaceFolders?: () => readonly string[];
  /** Symlink resolver, injectable for tests. */
  readonly realpath?: (path: string) => Promise<string>;
  /** Platform tag for path-case comparison, injectable for tests. */
  readonly platform?: NodeJS.Platform;
}

/** Localized provenance note for a candidate, for the quick-pick. */
export function describeCandidate(candidate: NameCandidate): string {
  return isExactMatch(candidate.origin) ? fromStemsDescription() : nameMatchDescription();
}

export class NameResolver implements ElementPathResolver {
  constructor(private readonly options: NameResolverOptions) {}

  /**
   * Every design path [query] could mean, most certain first.
   *
   * The hierarchy is consulted **only when stems produced nothing**. A
   * stems file is a statement about this design written by a tool that
   * parsed the RTL; a hierarchy name match is an inference from an
   * identifier. Mixing them would bury the exact answers among guesses and
   * make the ordering meaningless.
   */
  async candidates(query: NameQuery): Promise<readonly NameCandidate[]> {
    const fromStems = this.options.index.candidatesFor(query);
    if (fromStems.length > 0) return fromStems;
    const hierarchy = this.options.hierarchy;
    if (hierarchy === undefined) return [];
    return await hierarchyCandidates(query.identifier, hierarchy);
  }

  /**
   * [ElementPathResolver] — what the "Send to <peer>" commands call.
   *
   * Returns *all* candidates, each carrying its provenance, and lets the
   * command's quick-pick do the asking. Returning one path would put the
   * guess where the user cannot see it.
   */
  async resolve(snapshot: EditorSelectionSnapshot): Promise<readonly ElementPathChoice[]> {
    const candidates = await this.candidates({
      fsPath: snapshot.fsPath,
      line: snapshot.line,
      identifier: snapshot.identifier,
    });
    return candidates.map((candidate) => ({
      path: candidate.path,
      description: describeCandidate(candidate),
    }));
  }

  /**
   * Forward direction: where is [path] declared?
   *
   * ### Why the containment check is here and not at the call site
   *
   * A stems file is workspace content — generated by a tool, often
   * checked in, and entirely capable of naming `/etc/passwd` or
   * `../../../.ssh/id_ed25519` as a `sourceFile`. It is not a manifest we
   * wrote. Anything derived from one that reaches
   * `openTextDocument` therefore passes the same §11 gate a peer-supplied
   * `file_path` does, using the *same function* — `resolveWorkspacePath`.
   * A second containment implementation would be a second thing to get
   * wrong, and the one that is wrong is always the copy.
   *
   * With no `workspaceFolders` supplied there is no folder the user has
   * consented to, so every path is refused. That is the same answer
   * `resolveWorkspacePath` gives, reached without pretending otherwise.
   */
  async sourceLocationFor(path: string): Promise<ResolvedSourceLocation> {
    const [best] = this.options.index.locationsFor(path);
    if (best === undefined) return { ok: false, reason: 'unknown-path' };

    const resolved = await resolveWorkspacePath(best.sourceFile, {
      workspaceFolders: this.options.workspaceFolders?.() ?? [],
      ...(this.options.realpath !== undefined ? { realpath: this.options.realpath } : {}),
      ...(this.options.platform !== undefined ? { platform: this.options.platform } : {}),
    });
    if (!resolved.ok) return { ok: false, reason: resolved.reason };
    return { ok: true, fsPath: resolved.fsPath, lineNumber: best.lineNumber };
  }
}
